name: Hello World Manual

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      
      - name: Print Date
        run: date
      
      - name: Print Environment
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Triggered by: ${{ github.actor }}"
